### PR TITLE
Write an installer for macos

### PR DESCRIPTION
**Pull request by joschaschmiedt**

### CODE REVIEW

**Comment by joschaschmiedt** [comment]
The macOS installer [currently fails](https://github.com/neuro-conda/neuro-conda/actions/runs/4280821641/jobs/7453060372#step:4:225) using the GitHub Action with
```
Could not solve for environment specs
Encountered problems while solving:
  - nothing provides requested pycuda 2022.2**

The environment can't be solved, aborting the operation
```
@pantaray, does that also happen locally?

**Comment by pantaray** [comment]
Hi! Nope, but I only tested it on my Intel MBP from 2015. I'll test-drive the entire thing on one of our M1 Mac Minis today. I also noticed, that the installer crashes, if one attempts to launch it within an activated conda installation. This can be circumvented, of course but should we include some sort of interactive road block, that asks if the user really wants to install neuo-conda alongside an existing conda installation? What do you think?

**Comment by pantaray** [comment]
Yup, okay, perfect! In the spirit of our planned env variables (`ncEditor` etc.) I could include`ncNoninteractive`. If set, no user input is queried and the installer just does its thing. Would that work for you?

**Comment by joschaschmiedt** [comment]
> Yup, okay, perfect! In the spirit of our planned env variables (`ncEditor` etc.) I could include`ncNoninteractive`. If set, no user input is queried and the installer just does its thing. Would that work for you?

Good idea! Thanks for testing the macs.

**Comment by pantaray** [comment]
Took a bit of trial-and-erroring but I think this works now. I think we might want to merge now and include more tests (e.g., uninstalling) later. Is that okay with you?

**Pull request merged**
